--[[
	author: Veg
	last update: 2020-09-04
	Big thanks to Aussiemon from whoms't mods I learned how to make hotkeys -
	This file is largely structured the same as his Creature Spawner's data Lua.
]]
local mod = get_mod("givebuff")

-- e.g. Stuff like Stormfiend DOT
mod.enemy_buffs = {}
-- e.g. Natural Bond, Barkskin, etc.
mod.equipment_buffs = {}
-- e.g. Hero Passives like Ironheart (Zealot Undying) but also Grail Knight stuff
mod.hero_buffs = {}
-- e.g. Mutationy bits
mod.mutation_buffs = {}
-- i.e. Strength, Concoction, Speed - includes decanter modifiers
mod.potion_buffs = {}
-- e.g. Swift Slaying
mod.weapon_buffs = {}
-- e.g. Weird weave things
mod.weave_buffs = {}
-- e.g. Earthblood and things that happen in twitch
-- Note that twitch stuff is not always a "buff" so implementation is different
mod.twitch_buffs = {
	-- "twitch_add_cooldown_potion_buff",
	-- "twitch_add_damage_potion_buff",
	-- "twitch_add_speed_potion_buff",
	-- "twitch_give_cooldown_reduction_potion",
	-- "twitch_give_damage_boost_potion",
	-- "twitch_give_fire_grenade_t1",
	-- "twitch_give_first_aid_kit",
	-- "twitch_give_frag_grenade_t1",
	-- "twitch_give_healing_draught",
	-- "twitch_give_speed_boost_potion",
	-- "twitch_grimoire_health_debuff",
	-- "twitch_health_degen",
	-- "twitch_health_regen",
	-- "twitch_no_overcharge_no_ammo_reloads",
	-- "twitch_spawn_berzerkers",
	-- "twitch_spawn_chaos_spawn",
	-- "twitch_spawn_chaos_troll",
	-- "twitch_spawn_corruptor_sorcerer",
	-- "twitch_spawn_death_squad_chaos_warrior",
	-- "twitch_spawn_death_squad_storm_vermin",
	-- "twitch_spawn_explosive_loot_rats",
	-- "twitch_spawn_gutter_runner",
	-- "twitch_spawn_horde_vector_blob",
	-- "twitch_spawn_loot_rat_fiesta",
	-- "twitch_spawn_minotaur",
	-- "twitch_spawn_pack_master",
	-- "twitch_spawn_plague_monks",
	-- "twitch_spawn_poison_wind_globadier",
	-- "twitch_spawn_rat_ogre",
	-- "twitch_spawn_ratling_gunner",
	-- "twitch_spawn_stormfiend",
	-- "twitch_spawn_vortex_sorcerer",
	-- "twitch_spawn_warpfire_thrower",
	-- "twitch_vote_activate_bloodlust",
	-- "twitch_vote_activate_chasing_spirits",
	-- "twitch_vote_activate_darkness",
	-- "twitch_vote_activate_flames",
	-- "twitch_vote_activate_leash",
	-- "twitch_vote_activate_lightning_strike",
	-- "twitch_vote_activate_realism",
	-- "twitch_vote_activate_root",
	-- "twitch_vote_activate_root_all",
	-- "twitch_vote_activate_slayer_curse",
	-- "twitch_vote_activate_splitting_enemies",
	-- "twitch_vote_activate_ticking_bomb",
	-- "twitch_vote_critical_strikes",
	-- "twitch_vote_full_temp_hp",
	-- "twitch_vote_hemmoraghe",
	-- "twitch_vote_infinite_bombs",
	-- "twitch_vote_invincibility",
	-- "twitch_cooldown_reduction_boost",
	-- "twitch_damage_boost",
	-- "twitch_speed_boost",
	-- "twitch_grimoire_health_debuff",
	-- "twitch_health_degen",
	-- "twitch_health_regen",
	-- "twitch_no_overcharge_no_ammo_reloads",
	-- "twitch_vote_buff_critical_strikes",
	-- "twitch_vote_buff_hemmoraghe",
	-- "twitch_vote_buff_infinite_bombs",
	-- "twitch_vote_buff_invincibility",
	-- "twitch_vote_buff_root",
}

-- Special handling of twitch things that affect only one player
-- mod.twitch_buffs_single = {
-- 	twitch_health_degen = true,
-- 	twitch_vote_activate_root = true,
-- 	twitch_vote_hemmoraghe = true,
-- 	twitch_vote_infinite_bombs = true,
-- 	twitch_vote_invincibility = true,
-- }
-- mod.twitch_buffs_item = {
-- 	twitch_give_cooldown_reduction_potion = true,
-- 	twitch_give_damage_boost_potion = true,
-- 	twitch_give_fire_grenade_t1 = true,
-- 	twitch_give_first_aid_kit = true,
-- 	twitch_give_frag_grenade_t1 = true,
-- 	twitch_give_healing_draught = true,
-- 	twitch_give_speed_boost_potion = true,
-- }
-- mod.twitch_buffs_item_map = {
-- 	twitch_give_cooldown_reduction_potion = "cooldown_reduction_potion",
-- 	twitch_give_damage_boost_potion = "damage_boost_potion",
-- 	twitch_give_fire_grenade_t1 = "fire_grenade_t1",
-- 	twitch_give_first_aid_kit = "first_aid_kit",
-- 	twitch_give_frag_grenade_t1 = "frag_grenade_t1",
-- 	twitch_give_healing_draught = "healing_draught",
-- 	twitch_give_speed_boost_potion = "speed_boost_potion",
-- }

-- e.g. Other but not "all"
mod.misc_buffs = {}
mod.all_buffs = {}

mod.buff_category_names = {
	"enemy",
	"equipment",
	"hero",
	"mutation",
	"potion",
	"twitch",
	"weapon",
	"weave",
	"misc",
	"all"
}

-- Note that any buff template that doesn't appear here will still be available under "all"
mod.buff_categories = {
	aoe_poison_dot = {"weapon",},
	arrow_poison_dot = {"weapon",},
	attack_speed_from_proc = {"weapon",},
	bardin_ironbreaker_ability_cooldown_on_damage_taken = {"hero",},
	bardin_ironbreaker_ability_cooldown_on_hit = {"hero",},
	bardin_ironbreaker_activated_ability = {"hero",},
	bardin_ironbreaker_activated_ability_attack_intensity_decay_increase = {"hero",},
	bardin_ironbreaker_activated_ability_block_cost = {"hero",},
	bardin_ironbreaker_activated_ability_power_buff = {"hero",},
	bardin_ironbreaker_activated_ability_taunt_range_and_duration = {"hero",},
	bardin_ironbreaker_activated_ability_taunt_range_and_duration_attack_intensity_decay_increase = {"hero",},
	bardin_ironbreaker_activated_ability_taunt_range_and_duration_block_cost = {"hero",},
	bardin_ironbreaker_bloodlust = {"hero",},
	bardin_ironbreaker_conqueror = {"hero",},
	bardin_ironbreaker_cooldown_reduction_on_kill_while_full_stamina = {"hero",},
	bardin_ironbreaker_decreased_overcharge = {"hero",},
	bardin_ironbreaker_drakefire_attack_speed = {"hero",},
	bardin_ironbreaker_drakefire_changing_attack_speed = {"hero",},
	bardin_ironbreaker_drakefire_changing_ranged_power = {"hero",},
	bardin_ironbreaker_drakefire_ranged_power = {"hero",},
	bardin_ironbreaker_gromril_antistun = {"hero",},
	bardin_ironbreaker_gromril_armour = {"hero",},
	bardin_ironbreaker_gromril_attack_speed = {"hero",},
	bardin_ironbreaker_gromril_buff = {"hero",},
	bardin_ironbreaker_gromril_delay = {"hero",},
	bardin_ironbreaker_gromril_delay_short = {"hero",},
	bardin_ironbreaker_gromril_rising_anger = {"hero",},
	bardin_ironbreaker_gromril_stagger = {"hero",},
	bardin_ironbreaker_gromril_stamina_regen = {"hero",},
	bardin_ironbreaker_increased_ranged_attack_speed = {"hero",},
	bardin_ironbreaker_increased_ranged_power = {"hero",},
	bardin_ironbreaker_party_power_on_blocked_attacks_add = {"hero",},
	bardin_ironbreaker_party_power_on_blocked_attacks_buff = {"hero",},
	bardin_ironbreaker_passive_increased_defence = {"hero",},
	bardin_ironbreaker_passive_increased_stamina = {"hero",},
	bardin_ironbreaker_passive_reduced_stun_duration = {"hero",},
	bardin_ironbreaker_power_on_blocked_attacks_add = {"hero",},
	bardin_ironbreaker_power_on_blocked_attacks_buff = {"hero",},
	bardin_ironbreaker_power_on_blocked_attacks_remove_damage = {"hero",},
	bardin_ironbreaker_power_on_blocked_attacks_remove_stagger = {"hero",},
	bardin_ironbreaker_power_on_nearby_allies = {"hero",},
	bardin_ironbreaker_power_on_nearby_allies_buff = {"hero",},
	bardin_ironbreaker_refresh_gromril_armour = {"hero",},
	bardin_ironbreaker_regen_stamina_on_block_broken = {"hero",},
	bardin_ironbreaker_regen_stamina_on_charged_attacks = {"hero",},
	bardin_ironbreaker_regen_stamina_on_charged_attacks_buff = {"hero",},
	bardin_ironbreaker_stacking_buff_gromril = {"hero",},
	bardin_ironbreaker_vanguard = {"hero",},
	bardin_ranger_ability_cooldown_on_damage_taken = {"hero",},
	bardin_ranger_ability_cooldown_on_hit = {"hero",},
	bardin_ranger_ability_free_grenade_buff = {"hero",},
	bardin_ranger_ability_free_grenade_remove = {"hero",},
	bardin_ranger_activated_ability = {"hero",},
	bardin_ranger_activated_ability_stealth_outside_of_smoke = {"hero",},
	bardin_ranger_attack_speed = {"hero",},
	bardin_ranger_conqueror = {"hero",},
	bardin_ranger_cooldown_on_reload = {"hero",},
	bardin_ranger_increased_melee_damage_on_no_ammo_add = {"hero",},
	bardin_ranger_increased_melee_damage_on_no_ammo_remove = {"hero",},
	bardin_ranger_melee_damage_on_no_ammo = {"hero",},
	bardin_ranger_movement_speed = {"hero",},
	bardin_ranger_passive = {"hero",},
	bardin_ranger_passive_consumeable_dupe_grenade = {"hero",},
	bardin_ranger_passive_consumeable_dupe_healing = {"hero",},
	bardin_ranger_passive_consumeable_dupe_potion = {"hero",},
	bardin_ranger_passive_increased_ammunition = {"hero",},
	bardin_ranger_passive_reload_speed = {"hero",},
	bardin_ranger_reaper = {"hero",},
	bardin_ranger_reduced_damage_taken_headshot = {"hero",},
	bardin_ranger_reduced_damage_taken_headshot_buff = {"hero",},
	bardin_ranger_reload_speed_on_multi_hit_add = {"hero",},
	bardin_ranger_reload_speed_on_multi_hit_buff = {"hero",},
	bardin_ranger_smoke_attack = {"hero",},
	bardin_ranger_smoke_attack_buff = {"hero",},
	bardin_ranger_smoke_heal = {"hero",},
	bardin_ranger_smoke_heal_buff = {"hero",},
	bardin_ranger_vanguard = {"hero",},
	bardin_slayer_ability_cooldown_on_damage_taken = {"hero",},
	bardin_slayer_ability_cooldown_on_hit = {"hero",},
	bardin_slayer_activated_ability = {"hero",},
	bardin_slayer_activated_ability_leap_damage_add = {"hero",},
	bardin_slayer_activated_ability_leap_damage_buff = {"hero",},
	bardin_slayer_activated_ability_leap_damage_remove = {"hero",},
	bardin_slayer_activated_ability_movement = {"hero",},
	bardin_slayer_attack_speed_on_double_one_handed_weapons = {"hero",},
	bardin_slayer_attack_speed_on_double_one_handed_weapons_buff = {"hero",},
	bardin_slayer_bloodlust = {"hero",},
	bardin_slayer_conqueror = {"hero",},
	bardin_slayer_crit_chance = {"hero",},
	bardin_slayer_damage_reduction_on_melee_charge_action = {"hero",},
	bardin_slayer_damage_reduction_on_melee_charge_action_buff = {"hero",},
	bardin_slayer_damage_taken_capped = {"hero",},
	bardin_slayer_passive_attack_speed = {"hero",},
	bardin_slayer_passive_cooldown_reduction_on_max_stacks = {"hero",},
	bardin_slayer_passive_increased_max_stacks = {"hero",},
	bardin_slayer_passive_movement_speed = {"hero",},
	bardin_slayer_passive_stacking_damage_buff = {"hero",},
	bardin_slayer_passive_stacking_damage_buff_on_hit = {"hero",},
	bardin_slayer_passive_uninterruptible_heavy = {"hero",},
	bardin_slayer_passive_uninterruptible_leap = {"hero",},
	bardin_slayer_power_on_double_two_handed_weapons = {"hero",},
	bardin_slayer_power_on_double_two_handed_weapons_buff = {"hero",},
	bardin_slayer_push_on_dodge = {"hero",},
	bardin_slayer_reaper = {"hero",},
	bardin_survival_ale_buff = {"hero",},
	beam_burning_dot = {"weapon",},
	beam_burning_dot_infinite = {"weapon",},
	beer_bottle_pickup_cooldown = {"hero",},
	bile_troll_vomit_face_base = {"enemy",},
	bile_troll_vomit_face_slowdown = {"enemy",},
	bile_troll_vomit_ground_base = {"enemy",},
	bile_troll_vomit_ground_slowdown = {"enemy",},
	blightreaper_curse = {"misc",},
	bloodlust = {"misc",}, -- Attached to other buff template
	bloodlust_debuff = {"misc",}, -- Attached to other buff template
	burning_1W_dot = {"hero",},
	burning_1W_dot_infinite = {"hero",},
	burning_1W_dot_unchained_pulse = {"hero",},
	burning_1W_dot_unchained_push = {"hero",},
	burning_3W_dot = {"hero",},
	burning_3W_dot_infinite = {"hero",},
	burning_dot = {"hero",},
	burning_dot_fire_grenade = {"hero",},
	burning_dot_infinite = {"hero",},
	burning_flamethrower_dot = {"hero",},
	burning_flamethrower_dot_infinite = {"hero",},
	catacombs_corpse_pit = {"misc",},
	celebrate_group = {"misc",}, -- A Quiet Drink?
	cemetery_floor_plague_slowdown = {"misc",},
	cemetery_plague_floor = {"misc",},
	change_dodge_distance = {"misc",},
	change_dodge_speed = {"misc",},
	chaos_zombie_explosion = {"misc",},
	conqueror = {"misc",}, -- ?
	consecutive_shot_buff = {}, -- ?
	consecutive_shot_debuff = {}, -- ?
	cooldown_reduction_potion = {"potion",},
	cooldown_reduction_potion_increased = {"potion",},
	cooldown_reduction_potion_reduced = {"potion",},
	corpse_explosion_default = {"hero",},
	corpse_pit_slowdown = {"misc",},
	custom_dmg_taken = {}, -- UI Tweaks
	custom_dps = {}, -- UI Tweaks
	custom_dps_timed = {}, -- UI Tweaks
	custom_scavenger = {}, -- UI Tweaks
	custom_temp_hp = {}, -- UI Tweaks
	custom_wounded = {}, -- UI Tweaks
	damage_boost_potion = {"potion",},
	damage_boost_potion_increased = {"potion",},
	damage_boost_potion_reduced = {"potion",},
	damage_taken_from_proc = {}, -- ?
	damage_taken_powerful_elites = {}, -- ?
	damage_volume_generic_dot = {}, -- ?
	defence_debuff_enemies = {"equipment","hero","misc"}, -- Shrapnel?
	dummy_stagger = {}, -- ?
	end_zone_invincibility = {"misc",}, -- ( ͡° ͜ʖ ͡°)
	enemy_penny_curse = {}, -- ?
	enemy_penny_curse_pulse = {}, -- ?
	falling_down_effect = {}, -- ?
	fatigue_regen_from_proc = {"hero",},
	finesse_unbalance = {}, -- ?
	grimoire_health_debuff = {"equipment","misc",},
	healing_standard = {"misc",},
	heavy_attack_shield_break = {"weapon",}, -- Shieldbreaker I assume
	hinder_career_ability = {}, -- ?
	hungover_effect = {"misc",},
	increase_damage_recieved_while_burning = {},
	increase_intoxication_level = {},
	increased_attack_speed = {"equipment",},
	increased_critical_hit_chance = {},
	increased_damage = {"hero","misc",}, -- Saltz?
	increased_damage_melee = {"hero","misc",}, -- Unchained?
	increased_healing_received = {"equipment","hero",},
	increased_max_alive_health = {},
	increased_max_fatigue = {"equipment",},
	increased_melee_damage_from_proc = {"hero",}, -- Bulwark?
	increased_movement_speed_from_proc = {"hero",},
	intoxication_base = {"misc",},
	intoxication_effect = {"misc",},
	intoxication_effect_max_stacks_vfx = {"misc",},
	intoxication_effect_vfx = {"misc",},
	intoxication_stagger = {"misc",},
	invincibility_standard = {"enemy",}, -- Banner?
	invulnerability_potion = {}, -- ( ͡° ͜ʖ ͡°)
	invulnerability_potion_increased = {}, -- ( ͡° ͜ʖ ͡°)
	invulnerability_potion_reduced = {}, -- ( ͡° ͜ʖ ͡°)
	kerillian_maidenguard_ability_cooldown_on_damage_taken = {"hero",},
	kerillian_maidenguard_ability_cooldown_on_hit = {"hero",},
	kerillian_maidenguard_activated_ability = {"hero",},
	kerillian_maidenguard_activated_ability_buff_on_enemy_hit = {"hero",},
	kerillian_maidenguard_activated_ability_crit_buff = {"hero",},
	kerillian_maidenguard_activated_ability_invis_duration = {"hero",},
	kerillian_maidenguard_block_cost = {"hero",},
	kerillian_maidenguard_bloodlust = {"hero",},
	kerillian_maidenguard_conqueror = {"hero",},
	kerillian_maidenguard_cooldown_on_nearby_allies_buff = {"hero",},
	kerillian_maidenguard_crit_chance = {"hero",},
	kerillian_maidenguard_improved_dodge = {"hero",},
	kerillian_maidenguard_improved_dodge_speed = {"hero",},
	kerillian_maidenguard_insta_ress = {"hero",},
	kerillian_maidenguard_insta_ress_buff = {"hero",},
	kerillian_maidenguard_max_ammo = {"hero",},
	kerillian_maidenguard_max_health = {"hero",},
	kerillian_maidenguard_passive_attack_speed_on_dodge = {"hero",},
	kerillian_maidenguard_passive_attack_speed_on_dodge_buff = {"hero",},
	kerillian_maidenguard_passive_damage_reduction = {"hero",},
	kerillian_maidenguard_passive_dodge = {"hero",},
	kerillian_maidenguard_passive_dodge_speed = {"hero",},
	kerillian_maidenguard_passive_increased_stamina = {"hero",},
	kerillian_maidenguard_passive_noclip_dodge_end = {"hero",},
	kerillian_maidenguard_passive_noclip_dodge_start = {"hero",},
	kerillian_maidenguard_passive_stamina_regen_aura = {"hero",},
	kerillian_maidenguard_passive_stamina_regen_buff = {"hero",},
	kerillian_maidenguard_passive_uninterruptible_revive = {"hero",},
	kerillian_maidenguard_power_level_on_unharmed = {"hero",},
	kerillian_maidenguard_power_level_on_unharmed_cooldown = {"hero",},
	kerillian_maidenguard_power_on_block_buff = {"hero",},
	kerillian_maidenguard_power_on_blocked_attacks_remove_damage = {"hero",},
	kerillian_maidenguard_power_on_dodge = {"hero",},
	kerillian_maidenguard_reaper = {"hero",},
	kerillian_maidenguard_ress_buff = {"hero",},
	kerillian_maidenguard_ress_time = {"hero",},
	kerillian_maidenguard_speed_on_block = {"hero",},
	kerillian_maidenguard_speed_on_block_buff = {"hero",},
	kerillian_maidenguard_speed_on_block_dummy_buff = {"hero",},
	kerillian_maidenguard_speed_on_push = {"hero",},
	kerillian_maidenguard_versatile_dodge = {"hero",},
	kerillian_shade_ability_cooldown_on_damage_taken = {"hero",},
	kerillian_shade_ability_cooldown_on_hit = {"hero",},
	kerillian_shade_ability_dot = {"hero",},
	kerillian_shade_activated_ability = {"hero",},
	kerillian_shade_activated_ability_quick_cooldown = {"hero",},
	kerillian_shade_activated_ability_quick_cooldown_buff = {"hero",},
	kerillian_shade_activated_ability_quick_cooldown_crit = {"hero",},
	kerillian_shade_activated_ability_restealth_delay = {"hero",},
	kerillian_shade_activated_ability_short = {"hero",},
	kerillian_shade_backstabs_replenishes_ammunition = {"hero",},
	kerillian_shade_backstabs_replenishes_ammunition_cooldown = {"hero",},
	kerillian_shade_bloodlust = {"hero",},
	kerillian_shade_conqueror = {"hero",},
	kerillian_shade_damage_reduction_on_critical_hit = {"hero",},
	kerillian_shade_damage_reduction_on_critical_hit_buff = {"hero",},
	kerillian_shade_end_activated_ability = {"hero",},
	kerillian_shade_increased_critical_strike_damage = {"hero",},
	kerillian_shade_increased_damage_on_poisoned_or_bleeding_enemy = {"hero",},
	kerillian_shade_movement_speed = {"hero",},
	kerillian_shade_movement_speed_on_critical_hit = {"hero",},
	kerillian_shade_movement_speed_on_critical_hit_buff = {"hero",},
	kerillian_shade_passive = {"hero",},
	kerillian_shade_passive_backstab_killing_blow = {"hero",},
	kerillian_shade_passive_crit = {"hero",},
	kerillian_shade_passive_improved = {"hero",},
	kerillian_shade_passive_stealth_on_backstab_kill = {"hero",},
	kerillian_shade_regrowth = {"hero",},
	kerillian_shade_stacking_headshot_damage_on_headshot = {"hero",},
	kerillian_shade_stacking_headshot_damage_on_headshot_buff = {"hero",},
	kerillian_waywatcher_ability_cooldown_on_damage_taken = {"hero",},
	kerillian_waywatcher_ability_cooldown_on_hit = {"hero",},
	kerillian_waywatcher_activated_ability_cooldown = {"hero",},
	kerillian_waywatcher_activated_ability_piercing_shot = {"hero",},
	kerillian_waywatcher_activated_ability_restore_ammo_on_career_skill_special_kill = {"hero",},
	kerillian_waywatcher_attack_speed_on_ranged_headshot = {"hero",},
	kerillian_waywatcher_attack_speed_on_ranged_headshot_buff = {"hero",},
	kerillian_waywatcher_conqueror = {"hero",},
	kerillian_waywatcher_critical_bleed = {"hero",},
	kerillian_waywatcher_extra_arrow_melee_kill = {"hero",},
	kerillian_waywatcher_extra_arrow_melee_kill_buff = {"hero",},
	kerillian_waywatcher_movement_speed_on_special_kill = {"hero",},
	kerillian_waywatcher_movement_speed_on_special_kill_buff = {"hero",},
	kerillian_waywatcher_passive = {"hero",},
	kerillian_waywatcher_passive_increased_ammunition = {"hero",},
	kerillian_waywatcher_passive_increased_zoom = {"hero",},
	kerillian_waywatcher_passive_no_damage_dropoff = {"hero",},
	kerillian_waywatcher_projectile_ricochet = {"hero",},
	kerillian_waywatcher_reaper = {"hero",},
	kerillian_waywatcher_regrowth = {"hero",},
	knockdown_bleed = {},
	linesman_unbalance = {"weapon",},
	markus_huntsman_ability_cooldown_on_damage_taken = {"hero",},
	markus_huntsman_ability_cooldown_on_hit = {"hero",},
	markus_huntsman_activated_ability = {"hero",},
	markus_huntsman_activated_ability_cooldown = {"hero",},
	markus_huntsman_activated_ability_decrease_crouch_move_speed = {"hero",},
	markus_huntsman_activated_ability_decrease_crouch_move_speed_duration = {"hero",},
	markus_huntsman_activated_ability_decrease_dodge_distance = {"hero",},
	markus_huntsman_activated_ability_decrease_dodge_distance_duration = {"hero",},
	markus_huntsman_activated_ability_decrease_dodge_speed = {"hero",},
	markus_huntsman_activated_ability_decrease_dodge_speed_duration = {"hero",},
	markus_huntsman_activated_ability_decrease_move_speed = {"hero",},
	markus_huntsman_activated_ability_decrease_move_speed_duration = {"hero",},
	markus_huntsman_activated_ability_decrease_walk_move_speed = {"hero",},
	markus_huntsman_activated_ability_decrease_walk_move_speed_duration = {"hero",},
	markus_huntsman_activated_ability_duration = {"hero",},
	markus_huntsman_activated_ability_headshot_multiplier = {"hero",},
	markus_huntsman_activated_ability_headshot_multiplier_duration = {"hero",},
	markus_huntsman_activated_ability_increased_reload_speed = {"hero",},
	markus_huntsman_activated_ability_increased_reload_speed_duration = {"hero",},
	markus_huntsman_activated_ability_increased_zoom = {"hero",},
	markus_huntsman_activated_ability_increased_zoom_duration = {"hero",},
	markus_huntsman_ammo_on_special_kill = {"hero",},
	markus_huntsman_auto_headshot = {"hero",},
	markus_huntsman_auto_headshot_remove = {"hero",},
	markus_huntsman_bloodlust = {"hero",},
	markus_huntsman_conqueror = {"hero",},
	markus_huntsman_damage_reduction_on_monster_kill = {"hero",},
	markus_huntsman_damage_reduction_on_monster_kill_buff = {"hero",},
	markus_huntsman_damage_reduction_on_monster_kill_passive = {"hero",},
	markus_huntsman_debuff_defence_on_crit = {"hero",},
	markus_huntsman_defence_buff = {"hero",},
	markus_huntsman_defence_remove = {"hero",},
	markus_huntsman_end_activated_on_melee_hit = {"hero",},
	markus_huntsman_end_activated_on_melee_hit_duration = {"hero",},
	markus_huntsman_end_activated_on_ranged_hit = {"hero",},
	markus_huntsman_end_activated_on_ranged_hit_duration = {"hero",},
	markus_huntsman_headshot_damage = {"hero",},
	markus_huntsman_headshot_no_ammo_count = {"hero",},
	markus_huntsman_headshot_no_ammo_count_buff = {"hero",},
	markus_huntsman_headshot_no_ammo_count_counter = {"hero",},
	markus_huntsman_headshots_increase_reload_speed = {"hero",},
	markus_huntsman_headshots_increase_reload_speed_buff = {"hero",},
	markus_huntsman_increased_damage_to_wounded_enemies = {"hero",},
	markus_huntsman_invuln_flash = {"hero",},
	markus_huntsman_movement_speed = {"hero",},
	markus_huntsman_passive = {"hero",},
	markus_huntsman_passive_crit_aura = {"hero",},
	markus_huntsman_passive_crit_aura_buff = {"hero",},
	markus_huntsman_passive_crit_buff = {"hero",},
	markus_huntsman_passive_crit_buff_removal = {"hero",},
	markus_huntsman_passive_increased_ammunition = {"hero",},
	markus_huntsman_passive_melee_kills = {"hero",},
	markus_huntsman_passive_melee_kills_counter = {"hero",},
	markus_huntsman_passive_no_damage_dropoff = {"hero",},
	markus_huntsman_passive_on_crit = {"hero",},
	markus_huntsman_passive_on_headshot = {"hero",},
	markus_huntsman_passive_temp_health_on_headshot = {"hero",},
	markus_huntsman_power_on_headshot = {"hero",},
	markus_huntsman_power_on_headshot_buff = {"hero",},
	markus_huntsman_reload_speed_passive_stacks = {"hero",},
	markus_huntsman_reload_speed_passive_stacks_buff = {"hero",},
	markus_huntsman_stacking_damage_reduction_on_kills = {"hero",},
	markus_huntsman_ult_on_death = {"hero",},
	markus_huntsman_ult_on_death_delay = {"hero",},
	markus_huntsman_vanguard = {"hero",},
	markus_knight_ability_attack_speed_enemy_hit_blast = {"hero",},
	markus_knight_ability_attack_speed_enemy_hit_buff = {"hero",},
	markus_knight_ability_attack_speed_enemy_hit_charge = {"hero",},
	markus_knight_ability_cooldown_on_damage_taken = {"hero",},
	markus_knight_ability_cooldown_on_hit = {"hero",},
	markus_knight_ability_hit_target_damage_taken_blast = {"hero",},
	markus_knight_ability_hit_target_damage_taken_charge = {"hero",},
	markus_knight_ability_invulnerability_buff = {"hero",},
	markus_knight_activated_ability = {"hero",},
	markus_knight_attack_speed_on_push = {"hero",},
	markus_knight_attack_speed_on_push_buff = {"hero",},
	markus_knight_conqueror = {"hero",},
	markus_knight_cooldown_buff = {"hero",},
	markus_knight_cooldown_on_stagger_elite = {"hero",},
	markus_knight_damage_taken_ally_proximity = {"hero",},
	markus_knight_damage_taken_ally_proximity_buff = {"hero",},
	markus_knight_free_pushes_on_block = {"hero",},
	markus_knight_free_pushes_on_block_buff = {"hero",},
	markus_knight_guard = {"hero",},
	markus_knight_guard_buff = {"hero",},
	markus_knight_guard_defence = {"hero",},
	markus_knight_guard_defence_buff = {"hero",},
	markus_knight_improved_passive_defence_aura = {"hero",},
	markus_knight_improved_passive_defence_aura_buff = {"hero",},
	markus_knight_movement_speed_on_incapacitated_allies = {"hero",},
	markus_knight_movement_speed_on_incapacitated_allies_buff = {"hero",},
	markus_knight_passive = {"hero",},
	markus_knight_passive_block_cost_aura = {"hero",},
	markus_knight_passive_block_cost_aura_buff = {"hero",},
	markus_knight_passive_damage_reduction = {"hero",},
	markus_knight_passive_defence_aura = {"hero",},
	markus_knight_passive_defence_aura_range = {"hero",},
	markus_knight_passive_increased_stamina = {"hero",},
	markus_knight_passive_power_increase_buff = {"hero",},
	markus_knight_passive_range = {"hero",},
	markus_knight_power_level_impact = {"hero",},
	markus_knight_power_level_on_stagger_elite = {"hero",},
	markus_knight_power_level_on_stagger_elite_buff = {"hero",},
	markus_knight_reaper = {"hero",},
	markus_knight_vanguard = {"hero",},
	markus_mercenary_ability_cooldown_on_damage_taken = {"hero",},
	markus_mercenary_ability_cooldown_on_hit = {"hero",},
	markus_mercenary_activated_ability_cooldown_no_heal = {"hero",},
	markus_mercenary_activated_ability_damage_reduction = {"hero",},
	markus_mercenary_bloodlust = {"hero",},
	markus_mercenary_conqueror = {"hero",},
	markus_mercenary_counter_buff = {"hero",},
	markus_mercenary_crit_count = {"hero",},
	markus_mercenary_crit_count_buff = {"hero",},
	markus_mercenary_damage_on_enemy_proximity = {"hero",},
	markus_mercenary_dodge_range = {"hero",},
	markus_mercenary_dodge_speed = {"hero",},
	markus_mercenary_increased_damage_on_enemy_proximity = {"hero",},
	markus_mercenary_max_ammo = {"hero",},
	markus_mercenary_passive = {"hero",},
	markus_mercenary_passive_crit_chance = {"hero",},
	markus_mercenary_passive_defence = {"hero",},
	markus_mercenary_passive_hit_mass_override = {"hero",},
	markus_mercenary_passive_improved = {"hero",},
	markus_mercenary_passive_power_level = {"hero",},
	markus_mercenary_passive_proc = {"hero",},
	markus_mercenary_passive_uninterruptible_heavy = {"hero",},
	markus_mercenary_power_level_cleave = {"hero",},
	markus_mercenary_reaper = {"hero",},
	markus_questing_knight_ability_buff_on_kill = {"hero",},
	markus_questing_knight_ability_buff_on_kill_movement_speed = {"hero",},
	markus_questing_knight_ability_cooldown_on_damage_taken = {"hero",},
	markus_questing_knight_ability_cooldown_on_hit = {"hero",},
	markus_questing_knight_bloodlust = {"hero",},
	markus_questing_knight_charged_attacks_increased_power = {"hero",},
	markus_questing_knight_conqueror = {"hero",},
	markus_questing_knight_crit_can_insta_kill = {"hero",},
	markus_questing_knight_health_refund_over_time = {"hero",},
	markus_questing_knight_health_refund_over_time_delayed_heal = {"hero",},
	markus_questing_knight_kills_buff_power_stacking = {"hero",},
	markus_questing_knight_kills_buff_power_stacking_buff = {"hero",},
	markus_questing_knight_parry_increased_power = {"hero",},
	markus_questing_knight_parry_increased_power_buff = {"hero",},
	markus_questing_knight_passive_attack_speed = {"hero",},
	markus_questing_knight_passive_attack_speed_improved = {"hero",},
	markus_questing_knight_passive_cooldown_reduction = {"hero",},
	markus_questing_knight_passive_cooldown_reduction_improved = {"hero",},
	markus_questing_knight_passive_damage_taken = {"hero",},
	markus_questing_knight_passive_damage_taken_improved = {"hero",},
	markus_questing_knight_passive_health_regen = {"hero",},
	markus_questing_knight_passive_health_regen_improved = {"hero",},
	markus_questing_knight_passive_power_level = {"hero",},
	markus_questing_knight_passive_power_level_improved = {"hero",},
	markus_questing_knight_perk_first_target_damage = {"hero",},
	markus_questing_knight_perk_movement_speed = {"hero",},
	markus_questing_knight_perk_power_block = {"hero",},
	markus_questing_knight_push_arc = {"hero",},
	markus_questing_knight_stamina_reg = {"hero",},
	markus_questing_knight_vanguard = {"hero",},
	metal_mutator_damage_boost = {"weave","mutation",},
	metal_mutator_gromril_armour = {"weave","mutation",},
	movement_volume_generic_slowdown = {}, -- ?
	mutator_beasts_totem_buff = {"mutation",},
	mutator_bloodlust = {"mutation",},
	mutator_bloodlust_debuff = {"mutation",},
	mutator_death_attack_speed_player_buff = {"mutation",},
	mutator_fire_enemy_dot = {"mutation",},
	mutator_fire_mutator_bomb = {"mutation",},
	mutator_fire_player_dot = {"mutation",},
	mutator_life_damage_on_hit = {"mutation",},
	mutator_life_health_regeneration = {"mutation",},
	mutator_life_health_regeneration_stacks = {"mutation",},
	mutator_life_poison = {"mutation",},
	mutator_life_thorns_poison = {"mutation",},
	mutator_light_cleansing_curse_buff = {"mutation",},
	mutator_light_debuff = {"mutation",},
	mutator_metal_blade_dance = {"mutation",},
	mutator_metal_killing_blow = {"mutation",},
	mutator_player_dot = {"mutation",},
	mutator_shadow_damage_reduction = {"mutation",},
	mutator_ticking_bomb = {"mutation",},
	necklace_health_0001_buff = {"equipment",},
	necklace_health_0002_buff = {"equipment",},
	necklace_health_0003_buff = {"equipment",},
	necklace_stamina_0001_buff = {"equipment",},
	necklace_stamina_0002_buff = {"equipment",},
	necklace_stamina_0003_buff = {"equipment",},
	overcharged = {"hero",},
	overcharged_critical = {"hero",},
	overcharged_critical_no_attack_penalty = {"hero",},
	overcharged_no_attack_penalty = {"hero",},
	plague_wave_face_base = {}, -- ?
	plague_wave_face_slowdown = {}, -- ?
	plague_wave_ground_base = {}, -- ?
	plague_wave_ground_slowdown = {}, -- ?
	planted_casting_long_decrease_movement = {}, -- ?
	planted_charging_decrease_movement = {}, -- ?
	planted_decrease_movement = {}, -- ?
	planted_fast_decrease_movement = {}, -- ?
	planted_return_to_normal_crouch_movement = {}, -- ?
	planted_return_to_normal_movement = {}, -- ?
	planted_return_to_normal_walk_movement = {}, -- ?
	power_level_unbalance = {}, -- ?
	properties_ability_cooldown_reduction = {"equipment",},
	properties_attack_speed = {"equipment","weapon",},
	properties_block_cost = {"equipment","weapon",},
	properties_crit_boost = {"equipment","weapon",},
	properties_crit_chance = {"equipment","weapon",},
	properties_curse_resistance = {"equipment",},
	properties_fatigue_regen = {"equipment","weapon",},
	properties_health = {"equipment",},
	properties_movespeed = {"equipment",},
	properties_power_vs_armoured = {"equipment","weapon",},
	properties_power_vs_chaos = {"equipment","weapon",},
	properties_power_vs_frenzy = {"equipment","weapon",},
	properties_power_vs_large = {"equipment","weapon",},
	properties_power_vs_skaven = {"equipment","weapon",},
	properties_power_vs_unarmoured = {"equipment","weapon",},
	properties_protection_aoe = {"equipment",},
	properties_protection_chaos = {"equipment",},
	properties_protection_skaven = {"equipment",},
	properties_push_block_arc = {"equipment","weapon",},
	properties_respawn_speed = {"equipment",},
	properties_revive_speed = {"equipment",},
	properties_stamina = {"equipment","weapon",},
	ranged_power_vs_armored = {"equipment",},
	ranged_power_vs_frenzy = {"equipment",},
	ranged_power_vs_large = {"equipment",},
	ranged_power_vs_unarmored = {"equipment",},
	reaper = {}, -- ?
	reduced_damage_taken = {}, -- ?
	regrowth = {}, -- ?
	ring_attackspeed_0001_buff = {"equipment",},
	ring_attackspeed_0002_buff = {"equipment",},
	ring_attackspeed_0003_buff = {"equipment",},
	sack_decrease_movement = {}, -- Haha
	sienna_adept_ability_cooldown_on_damage_taken = {"hero",},
	sienna_adept_ability_cooldown_on_hit = {"hero",},
	sienna_adept_ability_trail = {"hero",},
	sienna_adept_ability_trail_double = {"hero",},
	sienna_adept_ability_trail_infinite = {"hero",},
	sienna_adept_activated_ability = {"hero",},
	sienna_adept_activated_ability_cooldown = {"hero",},
	sienna_adept_attack_speed_on_enemies_hit = {"hero",},
	sienna_adept_attack_speed_on_enemies_hit_buff = {"hero",},
	sienna_adept_bloodlust = {"hero",},
	sienna_adept_conqueror = {"hero",},
	sienna_adept_cooldown_reduction_on_burning_enemy_killed = {"hero",},
	sienna_adept_damage_reduction_on_ignited_enemy = {"hero",},
	sienna_adept_damage_reduction_on_ignited_enemy_buff = {"hero",},
	sienna_adept_improved_tranquility = {"hero",},
	sienna_adept_increased_burn_damage = {"hero",},
	sienna_adept_passive = {"hero",},
	sienna_adept_passive_charge_speed_increased = {"hero",},
	sienna_adept_passive_charge_speed_increased_buff = {"hero",},
	sienna_adept_passive_cooldown = {"hero",},
	sienna_adept_passive_improved = {"hero",},
	sienna_adept_passive_overcharge_charge_speed_increased = {"hero",},
	sienna_adept_passive_overcharge_charge_speed_increased_buff = {"hero",},
	sienna_adept_passive_ranged_damage = {"hero",},
	sienna_adept_passive_reset_on_damage_taken = {"hero",},
	sienna_adept_passive_reset_on_spell_used = {"hero",},
	sienna_adept_power_level_on_full_charge = {"hero",},
	sienna_adept_power_level_on_full_charge_buff = {"hero",},
	sienna_adept_reduced_non_burn_damage = {"hero",},
	sienna_adept_vanguard = {"hero",},
	sienna_scholar_ability_cooldown_on_damage_taken = {"hero",},
	sienna_scholar_ability_cooldown_on_hit = {"hero",},
	sienna_scholar_activated_ability_crit_refresh_cooldown = {"hero",},
	sienna_scholar_bloodlust = {"hero",},
	sienna_scholar_conqueror = {"hero",},
	sienna_scholar_crit_chance_above_health_threshold = {"hero",},
	sienna_scholar_crit_chance_above_health_threshold_buff = {"hero",},
	sienna_scholar_damage_taken_on_elite_or_special_kill = {"hero",},
	sienna_scholar_damage_taken_on_elite_or_special_kill_buff = {"hero",},
	sienna_scholar_increased_attack_speed = {"hero",},
	sienna_scholar_move_speed_on_critical_hit = {"hero",},
	sienna_scholar_move_speed_on_critical_hit_buff = {"hero",},
	sienna_scholar_overcharge_no_slow = {"hero",},
	sienna_scholar_passive = {"hero",},
	sienna_scholar_passive_crit_chance = {"hero",},
	sienna_scholar_passive_increased_attack_speed = {"hero",},
	sienna_scholar_passive_increased_attack_speed_from_overcharge = {"hero",},
	sienna_scholar_passive_increased_power_level_on_high_overcharge = {"hero",},
	sienna_scholar_passive_increased_power_level_on_high_overcharge_buff = {"hero",},
	sienna_scholar_passive_overcharge_pause_on_special_kill = {"hero",},
	sienna_scholar_passive_overcharge_pause_on_special_kill_buff = {"hero",},
	sienna_scholar_passive_ranged_damage = {"hero",},
	sienna_scholar_ranged_power_ascending_descending = {"hero",},
	sienna_scholar_ranged_power_ascending_descending_buff = {"hero",},
	sienna_scholar_reaper = {"hero",},
	sienna_unchained_ability_cooldown_on_damage_taken = {"hero",},
	sienna_unchained_ability_cooldown_on_hit = {"hero",},
	sienna_unchained_activated_ability = {"hero",},
	sienna_unchained_activated_ability_power_on_enemies_hit = {"hero",},
	sienna_unchained_activated_ability_power_on_enemies_hit_buff = {"hero",},
	sienna_unchained_activated_ability_pulse = {"hero",},
	sienna_unchained_attack_speed_on_high_overcharge = {"hero",},
	sienna_unchained_attack_speed_on_high_overcharge_buff = {"hero",},
	sienna_unchained_burn_push = {"hero",},
	sienna_unchained_burning_enemies_reduced_damage = {"hero",},
	sienna_unchained_conqueror = {"hero",},
	sienna_unchained_exploding_burning_enemies = {"hero",},
	sienna_unchained_health_to_cooldown_buff = {"hero",},
	sienna_unchained_health_to_ult = {"hero",},
	sienna_unchained_increased_vent_speed = {"hero",},
	sienna_unchained_passive = {"hero",},
	sienna_unchained_passive_increased_melee_power_on_overcharge = {"hero",},
	sienna_unchained_passive_melee_power_on_overcharge = {"hero",},
	sienna_unchained_passive_overcharged_blocks = {"hero",},
	sienna_unchained_push_arc_buff = {"hero",},
	sienna_unchained_reaper = {"hero",},
	sienna_unchained_reduced_damage_taken_after_venting = {"hero",},
	sienna_unchained_reduced_damage_taken_after_venting_buff = {"hero",},
	sienna_unchained_reduced_overcharge = {"hero",},
	sienna_unchained_reduced_passive_overcharge_after_venting_buff = {"hero",},
	sienna_unchained_reduced_vent_damage = {"hero",},
	sienna_unchained_vanguard = {"hero",},
	-- slayer_curse_debuff = {"mutation","twitch",},
	smiter_unbalance = {"hero",},
	speed_boost_potion = {"potion",},
	speed_boost_potion_increased = {"potion",},
	speed_boost_potion_reduced = {"potion",},
	stamina_regen = {"hero","equipment",},
	statue_decrease_movement = {}, -- ?
	stormfiend_warpfire_face_base = {"enemy",},
	stormfiend_warpfire_ground_base = {"enemy",},
	super_jump = {}, -- ?
	tank_unbalance = {"equipment",},
	tank_unbalance_buff = {"equipment",},
	temporary_health_degen = {}, -- ?
	ticking_bomb_decrease_movement = {"mutation",},
	trait_necklace_damage_taken_reduction_buff = {"equipment",},
	trait_necklace_damage_taken_reduction_on_heal = {"equipment",},
	trait_necklace_heal_self_on_heal_other = {"equipment",},
	trait_necklace_increased_healing_received = {"equipment",},
	trait_necklace_no_healing_health_regen = {"equipment",},
	trait_necklace_not_consume_healing = {"equipment",},
	trait_ring_all_potions = {"equipment",},
	trait_ring_not_consume_potion = {"equipment",},
	trait_ring_not_consume_potion_damage = {"equipment",},
	trait_ring_potion_duration = {"equipment",},
	trait_ring_potion_spread = {"equipment",},
	trait_trinket_grenade_damage_taken = {"equipment",},
	trait_trinket_grenade_damage_taken_buff = {"equipment",},
	trait_trinket_increase_grenade_radius = {"equipment",},
	trait_trinket_not_consume_grenade = {"equipment",},
	traits_heal_on_crit = {"equipment","hero",},
	traits_melee_attack_speed_on_crit = {"equipment",},
	traits_melee_attack_speed_on_crit_proc = {"equipment",},
	traits_melee_counter_push_power = {"equipment",},
	traits_melee_increase_damage_on_block = {"equipment",},
	traits_melee_increase_damage_on_block_proc = {"equipment",},
	traits_melee_shield_on_assist = {"equipment",},
	traits_melee_timed_block_cost = {"equipment",},
	traits_ranged_consecutive_hits_increase_power = {"equipment",},
	traits_ranged_increase_power_level_vs_armour_crit = {"equipment",},
	traits_ranged_movespeed_on_damage_taken = {"equipment",},
	traits_ranged_reduced_overcharge = {"equipment",},
	traits_ranged_remove_overcharge_on_crit = {"equipment",},
	traits_ranged_replenish_ammo_headshot = {"equipment",},
	traits_ranged_replenish_ammo_on_crit = {"equipment",},
	traits_ranged_restore_stamina_headshot = {"equipment",},
	traits_reduce_cooldown_on_crit = {"equipment",},
	traits_reduce_cooldown_on_crit_internal_cooldown = {"equipment",},
	tranquility = {"hero",},
	trinket_faster_respawn_tier1 = {"equipment",},
	trinket_faster_respawn_tier2 = {"equipment",},
	trinket_faster_revive_promo = {"equipment",},
	trinket_faster_revive_tier1 = {"equipment",},
	trinket_faster_revive_tier2 = {"equipment",},
	trinket_faster_revive_tier3 = {"equipment",},
	trinket_grenade_radius_tier1 = {"equipment",},
	trinket_grenade_radius_tier2 = {"equipment",},
	trinket_grenade_radius_tier3 = {"equipment",},
	trinket_hp_increase_kd_tier1 = {"equipment",},
	trinket_hp_increase_kd_tier2 = {"equipment",},
	trinket_hp_increase_kd_tier3 = {"equipment",},
	trinket_increase_luck_halloween = {"equipment",},
	trinket_increase_luck_promo = {"equipment",},
	trinket_increase_luck_tier1 = {"equipment",},
	trinket_increase_luck_tier2 = {"equipment",},
	trinket_increase_luck_tier3 = {"equipment",},
	trinket_increased_movement_speed_tier1 = {"equipment",},
	trinket_increased_movement_speed_tier2 = {"equipment",},
	trinket_increased_movement_speed_tier3 = {"equipment",},
	trinket_no_interruption_bandage = {"equipment",},
	trinket_no_interruption_revive = {"equipment",},
	trinket_not_consume_grenade_tier1 = {"equipment",},
	trinket_not_consume_grenade_tier2 = {"equipment",},
	trinket_not_consume_grenade_tier3 = {"equipment",},
	trinket_not_consume_medpack_tier1 = {"equipment",},
	trinket_not_consume_medpack_tier2 = {"equipment",},
	trinket_not_consume_medpack_tier3 = {"equipment",},
	trinket_not_consume_pickup_tier1 = {"equipment",},
	trinket_not_consume_pickup_tier2 = {"equipment",},
	trinket_not_consume_pickup_tier3 = {"equipment",},
	trinket_not_consume_potion_tier1 = {"equipment",},
	trinket_not_consume_potion_tier2 = {"equipment",},
	trinket_not_consume_potion_tier3 = {"equipment",},
	trinket_potion_spread_area_tier1 = {"equipment",},
	trinket_potion_spread_area_tier2 = {"equipment",},
	trinket_potion_spread_area_tier3 = {"equipment",},
	trinket_protection_gutter_runner_tier1 = {"equipment",},
	trinket_protection_gutter_runner_tier2 = {"equipment",},
	trinket_protection_gutter_runner_tier3 = {"equipment",},
	trinket_protection_pack_master_tier1 = {"equipment",},
	trinket_protection_pack_master_tier2 = {"equipment",},
	trinket_protection_pack_master_tier3 = {"equipment",},
	trinket_protection_poison_wind_tier1 = {"equipment",},
	trinket_protection_poison_wind_tier2 = {"equipment",},
	trinket_protection_poison_wind_tier3 = {"equipment",},
	trinket_protection_ratling_gunner_tier1 = {"equipment",},
	trinket_protection_ratling_gunner_tier2 = {"equipment",},
	trinket_protection_ratling_gunner_tier3 = {"equipment",},
	trinket_reduce_activated_ability_cooldown = {"equipment",},
	trinket_reduce_grimoire_penalty = {"equipment",},
	trinket_roll_dice_as_bright_wizard = {"equipment",},
	trinket_roll_dice_as_dwarf_ranger = {"equipment",},
	trinket_roll_dice_as_empire_soldier = {"equipment",},
	trinket_roll_dice_as_witch_hunter = {"equipment",},
	trinket_roll_dice_as_wood_elf = {"equipment",},
	trinket_shared_damage = {"equipment",},
	twitch_cooldown_reduction_boost = {"twitch",},
	twitch_damage_boost = {"twitch",},
	twitch_speed_boost = {"twitch",},
	twitch_grimoire_health_debuff = {"twitch",},
	twitch_health_degen = {"twitch",},
	twitch_health_regen = {"twitch",},
	twitch_no_overcharge_no_ammo_reloads = {"twitch",},
	twitch_vote_buff_critical_strikes = {"twitch",},
	twitch_vote_buff_hemmoraghe = {"twitch",},
	twitch_vote_buff_infinite_bombs = {"twitch",},
	twitch_vote_buff_invincibility = {"twitch",},
	twitch_vote_buff_root = {"twitch",},
	vanguard = {"mutation",},
	vermintide_face_base = {}, -- ?
	victor_bounty_blast_streak_buff = {"hero",},
	victor_bountyhunter_ability_cooldown_on_damage_taken = {"hero",},
	victor_bountyhunter_ability_cooldown_on_hit = {"hero",},
	victor_bountyhunter_activate_passive_on_melee_kill = {"hero",},
	victor_bountyhunter_activated_ability_blast_shotgun = {"hero",},
	victor_bountyhunter_activated_ability_passive_cooldown_reduction = {"hero",},
	victor_bountyhunter_activated_ability_railgun = {"hero",},
	victor_bountyhunter_activated_ability_reset_cooldown_on_stacks = {"hero",},
	victor_bountyhunter_attack_speed_on_no_ammo_buff = {"hero",},
	victor_bountyhunter_blessed_melee_buff = {"hero",},
	victor_bountyhunter_blessed_melee_damage_buff = {"hero",},
	victor_bountyhunter_blessed_ranged_buff = {"hero",},
	victor_bountyhunter_blessed_ranged_damage_buff = {"hero",},
	victor_bountyhunter_bloodlust = {"hero",},
	victor_bountyhunter_conqueror = {"hero",},
	victor_bountyhunter_debuff_defence_on_crit = {"hero",},
	victor_bountyhunter_increased_melee_damage_on_no_ammo_add = {"hero",},
	victor_bountyhunter_party_movespeed_on_ranged_crit = {"hero",},
	victor_bountyhunter_party_movespeed_on_ranged_crit_buff = {"hero",},
	victor_bountyhunter_passive_crit_buff = {"hero",},
	victor_bountyhunter_passive_crit_buff_removal = {"hero",},
	victor_bountyhunter_passive_crit_cooldown = {"hero",},
	victor_bountyhunter_passive_increased_ammunition = {"hero",},
	victor_bountyhunter_passive_infinite_ammo = {"hero",},
	victor_bountyhunter_passive_infinite_ammo_buff = {"hero",},
	victor_bountyhunter_passive_reduced_cooldown = {"hero",},
	victor_bountyhunter_passive_reload_speed = {"hero",},
	victor_bountyhunter_power_level_on_clip_size = {"hero",},
	victor_bountyhunter_power_level_on_clip_size_buff = {"hero",},
	victor_bountyhunter_power_on_no_ammo_buff = {"hero",},
	victor_bountyhunter_regrowth = {"hero",},
	victor_bountyhunter_reload_on_kill = {"hero",},
	victor_bountyhunter_restore_ammo_on_elite_kill = {"hero",},
	victor_bountyhunter_restore_ammo_on_kill_buff = {"hero",},
	victor_bountyhunter_stacking_damage_reduction_on_elite_or_special_kill = {"hero",},
	victor_bountyhunter_stacking_damage_reduction_on_elite_or_special_kill_buff = {"hero",},
	victor_bountyhunter_weapon_swap_buff = {"hero",},
	victor_witchhunter_ability_cooldown_on_damage_taken = {"hero",},
	victor_witchhunter_ability_cooldown_on_hit = {"hero",},
	victor_witchhunter_activated_ability_crit_buff = {"hero",},
	victor_witchhunter_activated_ability_guaranteed_crit_self_buff = {"hero",},
	victor_witchhunter_activated_ability_refund_cooldown_on_enemies_hit = {"hero",},
	victor_witchhunter_attack_speed_on_enemy_pinged = {"hero",},
	victor_witchhunter_attack_speed_on_enemy_pinged_buff = {"hero",},
	victor_witchhunter_bleed_on_critical_hit = {"hero",},
	victor_witchhunter_conqueror = {"hero",},
	victor_witchhunter_critical_hit_chance_on_ping_target_killed = {"hero",},
	victor_witchhunter_dodge_range = {"hero",},
	victor_witchhunter_dodge_speed = {"hero",},
	victor_witchhunter_guaranteed_crit_on_timed_block_add = {"hero",},
	victor_witchhunter_guaranteed_crit_on_timed_block_buff = {"hero",},
	victor_witchhunter_headshot_crit_killing_blow = {"hero",},
	victor_witchhunter_headshot_damage_increase = {"hero",},
	victor_witchhunter_headshot_multiplier_increase = {"hero",},
	victor_witchhunter_improved_damage_taken_ping = {"hero",},
	victor_witchhunter_max_ammo = {"hero",},
	victor_witchhunter_passive = {"hero",},
	victor_witchhunter_passive_block_cost_reduction = {"hero",},
	victor_witchhunter_passive_debuff = {"hero",},
	victor_witchhunter_passive_dodge_range = {"hero",},
	victor_witchhunter_passive_dodge_speed = {"hero",},
	victor_witchhunter_ping_target_crit_chance = {"hero",},
	victor_witchhunter_reaper = {"hero",},
	victor_witchhunter_regrowth = {"hero",},
	victor_witchhunter_stamina_regen_on_push = {"hero",},
	victor_witchhunter_stamina_regen_on_push_buff = {"hero",},
	victor_zealot_ability_cooldown_on_damage_taken = {"hero",},
	victor_zealot_ability_cooldown_on_hit = {"hero",},
	victor_zealot_activated_ability = {"hero",},
	victor_zealot_activated_ability_cooldown_stack_on_hit = {"hero",},
	victor_zealot_activated_ability_cooldown_stack_on_hit_buff = {"hero",},
	victor_zealot_activated_ability_ignore_death = {"hero",},
	victor_zealot_activated_ability_power_on_hit = {"hero",},
	victor_zealot_activated_ability_power_on_hit_buff = {"hero",},
	victor_zealot_attack_speed_on_health_percent = {"hero",},
	victor_zealot_attack_speed_on_health_percent_buff = {"hero",},
	victor_zealot_bloodlust = {"hero",},
	victor_zealot_conqueror = {"hero",},
	victor_zealot_counter_buff = {"hero",},
	victor_zealot_crit_count = {"hero",},
	victor_zealot_crit_count_buff = {"hero",},
	victor_zealot_gain_invulnerability_on_lethal_damage_taken = {"hero",},
	victor_zealot_invulnerability_cooldown = {"hero",},
	victor_zealot_invulnerability_on_lethal_damage_taken = {"hero",},
	victor_zealot_max_stamina_on_damage_taken = {"hero",},
	victor_zealot_move_speed_on_damage_taken = {"hero",},
	victor_zealot_move_speed_on_damage_taken_buff = {"hero",},
	victor_zealot_passive_damage = {"hero",},
	victor_zealot_passive_damage_taken = {"hero",},
	victor_zealot_passive_damage_taken_buff = {"hero",},
	victor_zealot_passive_healing_received = {"hero",},
	victor_zealot_passive_healing_received_buff = {"hero",},
	victor_zealot_passive_increased_damage = {"hero",},
	victor_zealot_passive_move_speed = {"hero",},
	victor_zealot_passive_move_speed_buff = {"hero",},
	victor_zealot_passive_uninterruptible_heavy = {"hero",},
	victor_zealot_power = {"hero",},
	victor_zealot_reaper = {"hero",},
	victor_zealot_reduced_damage_taken_buff = {"hero",},
	vortex_base = {"enemy",},
	vortex_slowdown = {"enemy",},
	warpfire_thrower_face_base = {"enemy",},
	warpfire_thrower_face_base_mutator = {"enemy",},
	warpfire_thrower_fire_slowdown = {"enemy",},
	warpfire_thrower_ground_base = {"enemy",},
	weapon_bleed_dot_dagger = {"weapon","equipment",},
	weapon_bleed_dot_maidenguard = {"weapon","hero",},
	weapon_bleed_dot_whc = {"weapon","hero",},
	weapon_trait_backstab = {"weapon","hero",},
	weapon_trait_bloodlust = {"weapon","equipment",}, -- ?
	weapon_trait_improved_push = {"weapon","equipment",},
	weapon_trait_riposte = {"weapon","hero",},
	weapon_trait_scavenge = {"weapon","equipment",},
	weapon_trait_uninterruptible = {"weapon","equipment",},
	weave_consecutive_shot_buff = {"weave",},
	weave_consecutive_shot_debuff = {"weave",},
	weave_properties_ability_cooldown_reduction = {"weave","equipment",},
	weave_properties_attack_speed = {"weave","equipment","weapon",},
	weave_properties_block_cost = {"weave","equipment","weapon",},
	weave_properties_crit_boost = {"weave","equipment","weapon",},
	weave_properties_crit_chance = {"weave","equipment","weapon",},
	weave_properties_curse_resistance = {"weave","equipment",},
	weave_properties_fatigue_regen = {"weave","equipment","weapon",},
	weave_properties_health = {"weave","equipment",},
	weave_properties_movespeed = {"weave","equipment",},
	weave_properties_power_vs_armoured = {"weave","equipment","weapon",},
	weave_properties_power_vs_chaos = {"weave","equipment","weapon",},
	weave_properties_power_vs_frenzy = {"weave","equipment","weapon",},
	weave_properties_power_vs_large = {"weave","equipment","weapon",},
	weave_properties_power_vs_skaven = {"weave","equipment","weapon",},
	weave_properties_power_vs_unarmoured = {"weave","equipment","weapon",},
	weave_properties_protection_aoe = {"weave","equipment",},
	weave_properties_protection_chaos = {"weave","equipment",},
	weave_properties_protection_skaven = {"weave","equipment",},
	weave_properties_push_block_arc = {"weave","equipment","weapon",},
	weave_properties_respawn_speed = {"weave","equipment",},
	weave_properties_revive_speed = {"weave","equipment",},
	weave_properties_stamina = {"weave","equipment","weapon",},
	weave_ranged_power_vs_armored = {"weave",},
	weave_ranged_power_vs_frenzy = {"weave",},
	weave_ranged_power_vs_large = {"weave",},
	weave_ranged_power_vs_unarmored = {"weave",},
	weave_trait_necklace_damage_taken_reduction_buff = {"weave","equipment",},
	weave_trait_necklace_damage_taken_reduction_on_heal = {"weave","equipment",},
	weave_trait_necklace_heal_self_on_heal_other = {"weave","equipment",},
	weave_trait_necklace_increased_healing_received = {"weave","equipment",},
	weave_trait_necklace_no_healing_health_regen = {"weave","equipment",},
	weave_trait_necklace_not_consume_healing = {"weave","equipment",},
	weave_trait_ring_all_potions = {"weave","equipment",},
	weave_trait_ring_not_consume_potion = {"weave","equipment",},
	weave_trait_ring_not_consume_potion_damage = {"weave","equipment",},
	weave_trait_ring_potion_duration = {"weave","equipment",},
	weave_trait_ring_potion_spread = {"weave","equipment",},
	weave_trait_trinket_grenade_damage_taken = {"weave","equipment",},
	weave_trait_trinket_grenade_damage_taken_buff = {"weave","equipment",},
	weave_trait_trinket_increase_grenade_radius = {"weave","equipment",},
	weave_trait_trinket_not_consume_grenade = {"weave","equipment",},
	weave_traits_heal_on_crit = {"weave","hero",},
	weave_traits_melee_attack_speed_on_crit = {"weave","equipment",},
	weave_traits_melee_attack_speed_on_crit_proc = {"weave","equipment",},
	weave_traits_melee_counter_push_power = {"weave","equipment",},
	weave_traits_melee_increase_damage_on_block = {"weave","equipment",},
	weave_traits_melee_increase_damage_on_block_proc = {"weave","equipment",},
	weave_traits_melee_shield_on_assist = {"weave","equipment",},
	weave_traits_melee_timed_block_cost = {"weave","equipment",},
	weave_traits_ranged_consecutive_hits_increase_power = {"weave","equipment",},
	weave_traits_ranged_increase_power_level_vs_armour_crit = {"weave","equipment",},
	weave_traits_ranged_movespeed_on_damage_taken = {"weave","equipment",},
	weave_traits_ranged_reduced_overcharge = {"weave","equipment",},
	weave_traits_ranged_remove_overcharge_on_crit = {"weave","equipment",},
	weave_traits_ranged_replenish_ammo_headshot = {"weave","equipment",},
	weave_traits_ranged_replenish_ammo_on_crit = {"weave","equipment",},
	weave_traits_ranged_restore_stamina_headshot = {"weave","equipment",},
	weave_traits_reduce_cooldown_on_crit = {"weave","equipment",},
	weave_traits_reduce_cooldown_on_crit_internal_cooldown = {"weave","equipment",},
}

local mod_data = {
	name = "Give Me the Buff",
	description = mod:localize("mod_description"),
	is_togglable = true,
	is_mutator = false,
	mutator_settings = {}
}

mod_data.options_widgets = {
	{
		["setting_name"] = "gb_team",
		["widget_type"] = "checkbox",
		["text"] = "Buff Team by Default",
		["tooltip"] = "When using hotkeys or not specified in command, buff team as well?",
		["default_value"] = true -- Default first option is enabled. In this case true
	},
	{
		["setting_name"] = "gb_list",
		["widget_type"] = "dropdown",
		["text"] = "Active Buff Category",
		["tooltip"] = "Choose which buffs are in the list:\n" ..
			"-- Enemy --\nBuffs that enemies have or inflict\n" ..
			"-- Equipment --\nBuffs from Necklaces, Charms, and Trinkets\n" ..
			"-- Hero --\nHero traits and passives\n" ..
			"-- Mutation --\nMutation stuff\n" ..
			"-- Potion --\nLook, potions!\n" ..
			"-- Twitch --\nTwitch-Mode boons and banes - note that a few twitch things will always apply to the whole team\n" ..
			"-- Weapons --\nWeapon traits and procs\n" ..
			"-- Weaves --\nBuffs related to weaves\n" ..
			"-- Misc --\nBuffs that don't really fit elsewhere (or I don't know what they do)\n" ..
			"-- All --\nEntire buff list (large)",
		["options"] = {
			{text = "Enemy", value = "enemy_buffs"},
			{text = "Equipment", value = "equipment_buffs"},
			{text = "Hero", value = "hero_buffs"},
			{text = "Mutation", value = "mutation_buffs"},
			{text = "Potion", value = "potion_buffs"},
			{text = "Twitch", value = "twitch_buffs"},
			{text = "Weapon", value = "weapon_buffs"},
			{text = "Weaves", value = "weave_buffs"},
			{text = "Misc", value = "misc_buffs"},
			{text = "All", value = "all_buffs"},
		},
		["default_value"] = "potion_buffs",
	},
	{
		["setting_name"] = "gb_key_activate",
		["widget_type"] = "keybind",
		["type"] = "pressed",
		["text"] = "Keybind: Give Buff",
		["tooltip"] = "Choose the keybinding that activates the selected buff.",
		["default_value"] = {},
		["action"] = "handle_give_buff",
	},
	{
		["setting_name"] = "gb_key_next",
		["widget_type"] = "keybind",
		["type"] = "pressed",
		["text"] = "Keybind: Next Buff",
		["tooltip"] = "Choose the keybinding that selects the next buff.",
		["default_value"] = {},
		["action"] = "handle_next_buff",
	},
	{
		["setting_name"] = "gb_key_prev",
		["widget_type"] = "keybind",
		["type"] = "pressed",
		["text"] = "Keybind: Previous Buff",
		["tooltip"] = "Choose the keybinding that selects the previous buff.",
		["default_value"] = {},
		["action"] = "handle_prev_buff",
	},
	{
		["setting_name"] = "gb_key_toggle_team",
		["widget_type"] = "keybind",
		["type"] = "pressed",
		["text"] = "Keybind: Toggle Team Buffs",
		["tooltip"] = "Choose the keybinding that toggles between giving buffs to yourself or the entire party.",
		["default_value"] = {},
		["action"] = "handle_toggle_team_buff",
	},
	{
		["setting_name"] = "gb_key_favourites_group",
		["widget_type"] = "group",
		["text"] = "Specific Buff Hotkeys",
		["sub_widgets"] = {
			{
				["setting_name"] = "gb_key_fav_concanter",
				["widget_type"] = "keybind",
				["text"] = "Decanter Concoction",
				["tooltip"] = "Every potion's effects with increased duration",
				["default_value"] = {},
				["action"] = "handle_fav_concanter",
			},
			{
				["setting_name"] = "gb_key_fav_regen",
				["widget_type"] = "keybind",
				["text"] = "Regeneration",
				["tooltip"] = "Regenerate green HP",
				["default_value"] = {},
				["action"] = "handle_fav_regen",
			},
			{
				["setting_name"] = "gb_key_fav_invincible",
				["widget_type"] = "keybind",
				["text"] = "Undying",
				["tooltip"] = "Temporarily unkillable",
				["default_value"] = {},
				["action"] = "handle_fav_invincible", -- twitch_vote_buff_invincibility
			},
			{
				["setting_name"] = "gb_key_fav_panic",
				["widget_type"] = "keybind",
				["text"] = "Panic!",
				["tooltip"] = "All of the above",
				["default_value"] = {},
				["action"] = "handle_fav_panic",
			},
			-- {
			-- 	["setting_name"] = "gb_key_fav_loadout",
			-- 	["widget_type"] = "keybind",
			-- 	["text"] = "Full Items",
			-- 	["tooltip"] = "Give self a random assortment of items",
			-- 	["default_value"] = {},
			-- 	["action"] = "handle_fav_loadout",
			-- },
		},
	},
}

return mod_data
